name: Tic Tac Toe

on:
  issues:
    types: [opened]

jobs:
  update-tic-tac-toe:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Play Game
        uses: im-pavan/tic-tac-toe-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
